### ISSUE TITLE
Design interfaces around dedicated types instead of generic u128 and such

### ISSUE THREAD

**Issue by frol** [near/units-rs#2]
You may take inspiration from here:

https://github.com/near/near-cli-rs/blob/8142a5ca995eeb24f26604fd0e1ee58d6572388d/src/common.rs#L116-L278

(it is far from being polished which is why we did not extract it from near-cli-rs yet)

**Comment by willemneal** [comment]
Totally agree.  This was just a POC.  I had been talking with @austinabell and @ChaoticTempest about adding a Balance type to the sdk as well.

Austin you mentioned the pain of defining operators on u128's but is it possible to have a type that is then extendable?

**Comment by austinabell** [comment]
> Totally agree. This was just a POC. I had been talking with @austinabell and @ChaoticTempest about adding a Balance type to the sdk as well.
> 
> Austin you mentioned the pain of defining operators on u128's but is it possible to have a type that is then extendable?

Yeah, the point I made before was that the type loses a lot of functionality with external crates even if you support every trait impl for this new type. Given that users might already be or will be using other crates for calculations, it would make this harder to use. I don't think that the tradeoff of the negatives with breaking and limiting changes to this type just so that it serializes to JSON as a string is worth it.

Definitely open to ideas on how this could be mitigated though. It's a completely different situation with the CLI because that won't be used as a dependency to build other Rust code on and this API doesn't matter that it isn't ergonomic or minimal.

**Comment by frol** [comment]
@austinabell I believe we can always escape the problem of integration with explicit `.to_yoctonear() -> u128` + `::from_yoctonear(u128)` methods:

```
let my_account_balance = NearBalance::from_yoctonear(10);
let my_new_account_balance = NearBalance::from_yoctonear(my_account_balance.to_yoctonear() * 100500);
```

I am a strong supporter of explicitness, especially in smart-contract context. I would even argue that our serialization should be changed from `my_method({"balance": "10230"})` to `my_method({"balance": {"yoctonear": "10230"}})` to disambiguate readers (e.g. on Ledger devices) on whether that balance is in NEAR or yoctonear. `struct NearBalance { yoctonear: u128 }` with standard `serde::{Serialize, Deserialize}` derives generate this structure for us for free.

**Comment by frol** [comment]
[near-gas](https://crates.io/crates/near-gas) and [near-token](https://crates.io/crates/near-token) crates were created to address this.
